name: pngquant
title: pngquant
version: 3.0.4
summary: Lossy PNG compressor
website: https://pngquant.org/
description: |
  Makes PNG images 3–4 times smaller with minimal loss of quality. Supports alpha transparency. Compatible with all browsers and operating systems.

  A command-line tool based on the libimagequant library.
license: GPL-3.0+
contact: kornel+snap@pngquant.org
donation: https://paypal.me/kornel
issues: https://github.com/kornelski/pngquant/issues
source-code: https://github.com/kornelski/pngquant
base: core24
confinement: strict

apps:
  pngquant:
    command: bin/pngquant
    plugs:
    - home

parts:
  pngquant:
    source-type: git
    source: https://github.com/kornelski/pngquant.git
    source-tag: 3.0.3
    plugin: rust
    build-packages:
      - gcc
      - libpng-dev
      - zlib1g-dev
      - liblcms2-dev
    stage-packages:
      - libpng16-16
      - zlib1g
      - liblcms2-2
